SELECT * FROM public.goldusers_signup
elect * from goldusers_signup

--Q1. What is the total sales revenue generated by each product?
SELECT 
    p.ProductName,
    SUM(s.salesPrice) AS TotalRevenue
FROM Sales s
JOIN Product p ON s.ProductID = p.ProductID
GROUP BY p.ProductName;

--Q2. Which 3 product has the highest sales revenue?
SELECT 
    p.ProductName,
    SUM(s.SalePrice) AS TotalRevenue
FROM Sales s
JOIN Product p ON s.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY TotalRevenue DESC
LIMIT 3;
	
--Q3. How many users have signed up for the service and has taken the
gold membership?
SELECT COUNT(DISTINCT g.UserID) AS GoldUsersCount
FROM goldusers_signup g;

--Q4. What is the revenue generated from gold users?
SELECT 
    SUM(s.salesprice) AS GoldRevenue
FROM Sales s
JOIN goldusers_signup g ON s.UserID = g.UserID;

--Q5. What is the total revenue generated from gold users?
SELECT 
    SUM(s.SalePrice) AS GoldRevenue
FROM Sales s
JOIN Gold_users_Signup g ON s.UserID = g.UserID;

--Q6. Which users has been a gold user for the How much of time?
select u.userid, current_date - g.signupdate as membership_days from  goldusers_signup g join users
u on u.userid=g.userid

--Q7. What is the most popular product among gold users?
SELECT 
    p.productname,
    COUNT(*) AS total_orders
FROM sales s
JOIN goldusers_signup g ON s.userid = g.userid
JOIN product p ON s.productid = p.productid
GROUP BY p.productname
ORDER BY total_orders DESC
LIMIT 1;

--Q8. What is the total sales revenue generated in each year?
SELECT 
    EXTRACT(YEAR FROM s.saledate) AS year,
    SUM(s.salesprice) AS total_revenue
FROM sales s
GROUP BY year
ORDER BY year;

--Q9. How has the sales revenue changed over the years?
SELECT 
    EXTRACT(YEAR FROM saledate) AS year,
    SUM(salesprice) AS total_revenue
FROM sales
GROUP BY year
ORDER BY year;

--Q10. What is the average Gold-signup compare to just sign up for the users?
SELECT 
    (SELECT COUNT(*) FROM goldusers_signup ) * 1.0 /
    (SELECT COUNT(*) FROM users) AS gold_signup_ratio;

--Q11. How many gold members users have order how many numbers of time ?
SELECT 
    s.userid,
    COUNT(*) AS order_count
FROM sales s
JOIN goldusers_signup g ON s.userid = g.userid
GROUP BY s.userid;

--Q12. What is the total amount each customer spend on Online Food delivery
select u.username,sum(s.salesprice) as total_spent from username u join sales s on u.userid=s.userid
group by u.username

--Q13. What is the frequency of customer visits to the online platform?
SELECT 
    s.userid, 
    COUNT(DISTINCT DATE(s.saledate)) AS visit_frequency
FROM sales s
GROUP BY s.userid;

--Q14. What was the first order purchase by each customer ?
SELECT 
    userid, 
    MIN(saledate) AS first_order_date
FROM sales
GROUP BY userid;

--Q15. What is the most purchase item on the menu and how many
--times was it purchased by all customers?
SELECT 
    p.productname, 
    COUNT(*) AS purchase_count
FROM sales s
JOIN product p ON s.productid = p.productid
GROUP BY p.productname
ORDER BY purchase_count DESC
LIMIT 1;

--Q16. Which item was most popular for each customer ?
SELECT productid, productname
FROM (
    SELECT 
        productid,
        productname,
        COUNT(*) AS purchase_count,
        RANK() OVER (PARTITION BY userid ORDER BY COUNT(*) DESC) AS rnk
    FROM sales
    GROUP BY productid, productname
) ranked
WHERE rnk = 1;

--Q17. Which item was purchase first by the customer after they
--become a member ?
SELECT 
    s.userid, 
    p.productname, 
    MIN(s.saledate) AS first_after_gold
FROM sales s
JOIN goldusers_signup g ON s.userid = g.userid
JOIN product p ON s.productid = p.productid
WHERE s.saledate >= g.signupdate
GROUP BY s.userid,p.productname

--Q18. Which item was purchase before the customer become a
--member ?
SELECT 
    s.userid, 
    p.productname, 
    MIN(s.saledate) AS first_before_gold
FROM sales s
JOIN goldusers_signup g ON s.userid = g.userid
JOIN product p ON s.productid = p.productid
WHERE s.saledate < g.signupdate
GROUP BY s.userid,p.productname

--Q19. What is the total orders and amount spent for each member
--before they become a member ?
SELECT 
    s.userid,
    COUNT(*) AS order_count,
    SUM(s.salesprice) AS total_spent
FROM sales s
JOIN goldusers_signup g ON s.userid = g.userid
WHERE s.saledate < g.signupdate
GROUP BY s.userid;

--20. Rank all the transactions for each member whenever they are a
--XYZ gold member for every non gold member Transaction marks as na
SELECT
    userid,
    CASE
        WHEN COUNT(*) > 5 THEN COUNT(*)::TEXT
        ELSE 'NA'
    END AS purchase_info
FROM sales
GROUP BY userid;
